language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-22

android:
  components:
    - platform-tool
    - tool
    - android-22
    - build-tools-22.0.1
    - extra-android-m2repository

script: 
  - cd offline-routing-sample
  - chmod u+x gradlew
  - ls -liA
  - ./gradlew assemble